# benjaminkley.conf

server {
    listen 80;
    server_name _;

    client_max_body_size 100M;

    # This block will handle all API calls
    location / {
        proxy_pass http://benjaminkley-app:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Serve static files collected by Django
    location /static/ {
        alias /app/staticfiles/;
    }

    location ^~ /media/ {
        add_header 'Access-Control-Allow-Origin' '*';
        alias /app/media/;
    }
}