# compose.yaml (MINIMAL - Django only)

services:
  # Your Django Application Service
  app:
    build: .
    container_name: benjaminkley-app
    ports:
      - "8001:8000" # Maps port 8000 inside the container to 8001 on your PC
    volumes:
      - .:/app
    env_file:
      - .env  # This will load your .env file with Railway credentials
    environment:
      - PORT=8000
      - DEBUG=True
      - TZ=UTC
      - MPLCONFIGDIR=/tmp/matplotlib
      - HOME=/tmp
    networks:
      - app-network
    command: >
      sh -c "mkdir -p /tmp/matplotlib &&
             . /opt/venv/bin/activate &&
             python manage.py migrate --no-input &&
             python manage.py collectstatic --no-input --clear &&
             gunicorn benjaminkley.wsgi --bind 0.0.0.0:8000 --timeout 120 --workers 2 --max-requests 1000"

networks:
  app-network:
    driver: bridge