# compose.yaml (MINIMAL - Django only)


services:
  app:
    build: .
    container_name: benjaminkley-app
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - PORT=8000
      - DEBUG=True
      - TZ=UTC
      - MPLCONFIGDIR=/tmp/matplotlib
      - HOME=/tmp
    networks:
      - app-network
    depends_on: []
    command: >
      sh -c "mkdir -p /tmp/matplotlib &&
             . /opt/venv/bin/activate &&
             python manage.py migrate --no-input &&
             python manage.py collectstatic --no-input --clear &&
             gunicorn benjaminkley.wsgi --bind 0.0.0.0:8000 --timeout 120 --workers 2 --max-requests 1000"

  celery:
    build: .
    container_name: benjaminkley-celery
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - TZ=UTC
      - MPLCONFIGDIR=/tmp/matplotlib
      - HOME=/tmp
    networks:
      - app-network
    depends_on: []
    command: >
      sh -c ". /opt/venv/bin/activate && celery -A benjaminkley worker --loglevel=info"


  celery-beat:
    build: .
    container_name: benjaminkley-celery-beat
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - TZ=UTC
      - MPLCONFIGDIR=/tmp/matplotlib
      - HOME=/tmp
    networks:
      - app-network
    depends_on: []
    command: >
      sh -c ". /opt/venv/bin/activate && celery -A benjaminkley beat --loglevel=info"

  nginx:
    image: nginx:1.25
    container_name: benjaminkley-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge