events {}

http {
    upstream django {
        server benjaminkley-app:8000;
    }

    server {
        listen 80;
        server_name _;

        client_max_body_size 100M;

        # Proxy requests to Django
        location / {
            proxy_pass http://django;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Serve static files collected by Django
        location /static/ {
            alias /app/staticfiles/;
            autoindex on;
        }

        # REMOVE /media/ block because media is served directly from S3
        # location /media/ {
        #     alias /app/media/;
        # }
    }
}