import io
import os
from datetime import datetime
from reportlab.lib import colors
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.units import inch
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image as ReportLabImage
from PIL import Image as PILImage, ImageDraw, ImageFont

BRAND_COLOR = colors.HexColor("#1A2B4C")
ACCENT_COLOR = colors.HexColor("#E8E8E8") 

def _header_footer(canvas, doc):
    canvas.saveState()
    width, height = LETTER
    canvas.setFillColor(BRAND_COLOR)
    canvas.rect(0, height - 1.2*inch, width, 1.2*inch, fill=1, stroke=0)
    canvas.setFillColor(colors.white)
    canvas.setFont("Helvetica-Bold", 24)
    canvas.drawString(0.5*inch, height - 0.75*inch, "3D Head Scan Report")
    canvas.setFont("Helvetica", 12)
    canvas.drawString(0.5*inch, height - 0.95*inch, "Generated by 3D Data Collection App")
    canvas.setStrokeColor(colors.lightgrey)
    canvas.line(0.5*inch, 0.75*inch, width - 0.5*inch, 0.75*inch)
    canvas.setFillColor(colors.gray)
    canvas.setFont("Helvetica", 9)
    date_str = datetime.now().strftime("%B %d, %Y")
    canvas.drawString(0.5*inch, 0.5*inch, f"Generated on: {date_str}")
    canvas.drawRightString(width - 0.5*inch, 0.5*inch, f"Page {doc.page}")
    canvas.restoreState()

def generate_scan_pdf(scan_object):
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer, 
        pagesize=LETTER,
        rightMargin=0.5*inch, leftMargin=0.5*inch, 
        topMargin=1.5*inch, bottomMargin=1*inch
    )
    
    styles = getSampleStyleSheet()
    elements = []
    styles.add(ParagraphStyle(name='SectionTitle', parent=styles['Heading2'], textColor=BRAND_COLOR, fontSize=16, spaceAfter=10))
    styles.add(ParagraphStyle(name='Label', parent=styles['Normal'], fontName='Helvetica-Bold', fontSize=10))
    styles.add(ParagraphStyle(name='Value', parent=styles['Normal'], fontSize=10))

    user_data = [
        [Paragraph("Patient Name:", styles['Label']), Paragraph(scan_object.user.get_full_name() or scan_object.user.email, styles['Value'])],
        [Paragraph("Scan Name:", styles['Label']), Paragraph(scan_object.name, styles['Value'])],
        [Paragraph("Scan ID:", styles['Label']), Paragraph(str(scan_object.id).split('-')[0].upper(), styles['Value'])],
        [Paragraph("Date:", styles['Label']), Paragraph(scan_object.created_at.strftime("%Y-%m-%d"), styles['Value'])],
        [Paragraph("Status:", styles['Label']), Paragraph(scan_object.get_status_display(), styles['Value'])],
    ]
    
    info_table = Table(user_data, colWidths=[1.5*inch, 3*inch])
    info_table.setStyle(TableStyle([
        ('VALIGN', (0,0), (-1,-1), 'TOP'),
        ('LINEBELOW', (0,0), (-1,-1), 0.5, colors.lightgrey),
        ('BOTTOMPADDING', (0,0), (-1,-1), 8),
        ('TOPPADDING', (0,0), (-1,-1), 8),
    ]))

    scan_image = None
    if scan_object.image_front:
        try:
            img_path = scan_object.image_front.path
            if os.path.exists(img_path):
                img = ReportLabImage(img_path)
                aspect = img.imageHeight / float(img.imageWidth)
                img.drawWidth = 2.5 * inch
                img.drawHeight = 2.5 * inch * aspect
                scan_image = img
        except Exception:
            pass

    if scan_image:
        layout_data = [[scan_image, info_table]]
        layout_table = Table(layout_data, colWidths=[3*inch, 4.5*inch])
        layout_table.setStyle(TableStyle([
            ('VALIGN', (0,0), (-1,-1), 'TOP'),
            ('ALIGN', (0,0), (0,0), 'CENTER'),
        ]))
        elements.append(layout_table)
    else:
        elements.append(info_table)

    elements.append(Spacer(1, 0.5*inch))

    elements.append(Paragraph("Biometric Measurements", styles['SectionTitle']))

    def format_cm(val):
        return f"{val} cm" if val is not None else "--"

    measure_data = [
        ["Measurement", "Value", "Measurement", "Value"],
        ["Head Width", format_cm(scan_object.head_width), "Under Chin (D)", format_cm(scan_object.under_chin_D)],
        ["Head Length", format_cm(scan_object.head_length), "Forehead to Back (B)", format_cm(scan_object.forehead_to_back_B)],
        ["Head Height", format_cm(scan_object.head_height), "Cross Measure (C)", format_cm(scan_object.cross_measurement_C)],
        ["Head Circ. (A)", format_cm(scan_object.head_circumference_A), "Ear to Ear", format_cm(scan_object.ear_to_ear)],
        ["Eye to Eye", format_cm(scan_object.eye_to_eye), "Ear Height", format_cm(scan_object.ear_height_G)],
        ["Eye -> Ear (F)", format_cm(scan_object.eye_corner_to_ear_F), "Cheek Guard Width", format_cm(scan_object.cheek_guard_width_N)],
    ]

    m_table = Table(measure_data, colWidths=[2*inch, 1.75*inch, 2*inch, 1.75*inch])
    m_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), BRAND_COLOR),
        ('TEXTCOLOR', (0,0), (-1,0), colors.white),
        ('ALIGN', (0,0), (-1,-1), 'LEFT'),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('BOTTOMPADDING', (0,0), (-1,0), 8),
        ('TOPPADDING', (0,0), (-1,0), 8),
        ('GRID', (0,0), (-1,-1), 0.5, colors.lightgrey),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, ACCENT_COLOR]),
    ]))
    
    elements.append(m_table)
    elements.append(Spacer(1, 0.4*inch))

    if scan_object.notes or scan_object.custom_field:
        elements.append(Paragraph("Additional Notes", styles['SectionTitle']))
        notes_data = []
        if scan_object.custom_field:
            notes_data.append([Paragraph("Custom Fit:", styles['Label']), Paragraph(scan_object.custom_field, styles['Value'])])
        if scan_object.notes:
            notes_data.append([Paragraph("User Notes:", styles['Label']), Paragraph(scan_object.notes, styles['Value'])])

        notes_table = Table(notes_data, colWidths=[1.5*inch, 6*inch])
        notes_table.setStyle(TableStyle([
            ('VALIGN', (0,0), (-1,-1), 'TOP'),
            ('BOX', (0,0), (-1,-1), 0.5, colors.grey),
            ('BACKGROUND', (0,0), (0,-1), ACCENT_COLOR),
            ('PADDING', (0,0), (-1,-1), 6),
        ]))
        elements.append(notes_table)
        elements.append(Spacer(1, 0.4*inch))

    current_dir = os.path.dirname(os.path.abspath(__file__))
    guide_path = os.path.join(current_dir, 'guide.png')

    if os.path.exists(guide_path):
        elements.append(Paragraph("Measurement Reference", styles['SectionTitle']))
        try:
            pil_img = PILImage.open(guide_path)
            draw = ImageDraw.Draw(pil_img)
            W, H = pil_img.size

            font_paths = [
                "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
                "/usr/share/fonts/dejavu/DejaVuSans-Bold.ttf",
                "C:\\Windows\\Fonts\\arialbd.ttf",
            ]
            
            font = None
            for path in font_paths:
                if os.path.exists(path):
                    try:
                        font = ImageFont.truetype(path, 40)
                        break
                    except Exception:
                        continue
            
            if not font:
                font = ImageFont.load_default()

            text_color = "#E74C3C"

            if scan_object.ear_to_ear:
                val = f"{scan_object.ear_to_ear} cm"
                draw.text((W * 0.25, H * 0.18), val, fill=text_color, font=font, anchor="mm")
            
            if scan_object.head_width:
                val = f"{scan_object.head_width} cm"
                draw.text((W * 0.75, H * 0.18), val, fill=text_color, font=font, anchor="mm")
            
            if scan_object.head_height:
                val = f"{scan_object.head_height} cm"
                draw.text((W * 0.25, H * 0.65), val, fill=text_color, font=font, anchor="mm")
            
            if scan_object.eye_to_eye:
                val = f"{scan_object.eye_to_eye} cm"
                draw.text((W * 0.75, H * 0.65), val, fill=text_color, font=font, anchor="mm")

            img_buffer = io.BytesIO()
            pil_img.save(img_buffer, format='PNG')
            img_buffer.seek(0)
            
            guide_img = ReportLabImage(img_buffer)
            aspect = guide_img.imageHeight / float(guide_img.imageWidth)
            guide_img.drawWidth = 6.5 * inch
            guide_img.drawHeight = 6.5 * inch * aspect
            
            guide_table = Table([[guide_img]], colWidths=[7*inch])
            guide_table.setStyle(TableStyle([('ALIGN', (0,0), (-1,-1), 'CENTER')]))
            elements.append(guide_table)

        except Exception:
            pass

    doc.build(elements, onFirstPage=_header_footer, onLaterPages=_header_footer)
    
    buffer.seek(0)
    return buffer